spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
      bindings:
        command-in-0:
          destination: account
          binder: rabbit
        supplier-out-0:
          destination: account
          binder: rabbit
        consumer-in-0:
          destination: result
          binder: rabbit
      function:
        definition: supplier;command;consumer;
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: account_service
    password: account0218
