spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.8.151
      bindings:
        dispatcher-in-0:
          destination: account
          binder: rabbit
        supplier-out-0:
          destination: account
          binder: rabbit
        consumer-in-0:
          destination: result
          binder: rabbit
      function:
        definition: supplier;dispatcher;consumer;
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.8.151:5430/bank
    username: account_service
    password: account0218