spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
      bindings:
        command-in-0:
          destination: merchant-command
          binder: rabbit
        query-in-0:
          destination: merchant-query
          binder: rabbit
        undo-in-0:
          destination: merchant-undo
          binder: rabbit
        supplier-out-0:
          destination: merchant-query
          binder: rabbit
        consumer-in-0:
          destination: result
          binder: rabbit
      function:
        definition: supplier;query;consumer;
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: merchant_service
    password: merchant0218
